"""Team nickname → (abbrev_or_None, LIKE fragment) for SQL filters."""

from __future__ import annotations

# Longer aliases first when matching. Values: (tm/abbrev or None, LIKE needle for team/team_full)
NBA_TEAMS: list[tuple[str, tuple[str | None, str]]] = [
    ("golden state warriors", ("GSW", "Golden State")),
    ("portland trail blazers", ("POR", "Portland")),
    ("minnesota timberwolves", ("MIN", "Minnesota")),
    ("oklahoma city thunder", ("OKC", "Oklahoma City")),
    ("new orleans pelicans", ("NOP", "New Orleans")),
    ("new orleans hornets", ("NOH", "New Orleans")),
    ("san antonio spurs", ("SAS", "San Antonio")),
    ("philadelphia 76ers", ("PHI", "Philadelphia")),
    ("philadelphia sixers", ("PHI", "Philadelphia")),
    ("los angeles clippers", ("LAC", "Clippers")),
    ("los angeles lakers", ("LAL", "Lakers")),
    ("la clippers", ("LAC", "Clippers")),
    ("la lakers", ("LAL", "Lakers")),
    ("new york knicks", ("NYK", "New York")),
    ("brooklyn nets", ("BKN", "Brooklyn")),
    ("new jersey nets", ("NJN", "New Jersey")),
    ("golden state", ("GSW", "Golden State")),
    ("trail blazers", ("POR", "Portland")),
    ("timberwolves", ("MIN", "Minnesota")),
    ("phoenix suns", ("PHO", "Phoenix")),
    ("dallas mavericks", ("DAL", "Dallas")),
    ("houston rockets", ("HOU", "Houston")),
    ("denver nuggets", ("DEN", "Denver")),
    ("utah jazz", ("UTA", "Utah")),
    ("miami heat", ("MIA", "Miami")),
    ("boston celtics", ("BOS", "Boston")),
    ("chicago bulls", ("CHI", "Chicago")),
    ("detroit pistons", ("DET", "Detroit")),
    ("indiana pacers", ("IND", "Indiana")),
    ("milwaukee bucks", ("MIL", "Milwaukee")),
    ("cleveland cavaliers", ("CLE", "Cleveland")),
    ("atlanta hawks", ("ATL", "Atlanta")),
    ("charlotte hornets", ("CHA", "Charlotte")),
    ("charlotte bobcats", ("CHA", "Charlotte")),
    ("washington wizards", ("WAS", "Washington")),
    ("orlando magic", ("ORL", "Orlando")),
    ("toronto raptors", ("TOR", "Toronto")),
    ("memphis grizzlies", ("MEM", "Memphis")),
    ("sacramento kings", ("SAC", "Sacramento")),
    ("warriors", ("GSW", "Golden State")),
    ("clippers", ("LAC", "Clippers")),
    ("mavericks", ("DAL", "Dallas")),
    ("cavaliers", ("CLE", "Cleveland")),
    ("cavs", ("CLE", "Cleveland")),
    ("celtics", ("BOS", "Boston")),
    ("lakers", ("LAL", "Lakers")),
    ("nuggets", ("DEN", "Denver")),
    ("rockets", ("HOU", "Houston")),
    ("spurs", ("SAS", "San Antonio")),
    ("sixers", ("PHI", "Philadelphia")),
    ("76ers", ("PHI", "Philadelphia")),
    ("knicks", ("NYK", "New York")),
    ("nets", (None, "Brooklyn")),
    ("heat", ("MIA", "Miami")),
    ("bulls", ("CHI", "Chicago")),
    ("pistons", ("DET", "Detroit")),
    ("pacers", ("IND", "Indiana")),
    ("bucks", ("MIL", "Milwaukee")),
    ("hawks", ("ATL", "Atlanta")),
    ("hornets", ("CHA", "Charlotte")),
    ("wizards", ("WAS", "Washington")),
    ("magic", ("ORL", "Orlando")),
    ("raptors", ("TOR", "Toronto")),
    ("grizzlies", ("MEM", "Memphis")),
    ("kings", ("SAC", "Sacramento")),
    ("jazz", ("UTA", "Utah")),
    ("thunder", ("OKC", "Oklahoma City")),
    ("pelicans", ("NOP", "New Orleans")),
    ("blazers", ("POR", "Portland")),
    ("wolves", ("MIN", "Minnesota")),
    ("suns", ("PHO", "Phoenix")),
]

NFL_TEAMS: list[tuple[str, tuple[str | None, str]]] = [
    ("kansas city chiefs", (None, "Chiefs")),
    ("san francisco 49ers", (None, "49ers")),
    ("tampa bay buccaneers", (None, "Buccaneers")),
    ("new england patriots", (None, "Patriots")),
    ("green bay packers", (None, "Packers")),
    ("new orleans saints", (None, "Saints")),
    ("philadelphia eagles", (None, "Eagles")),
    ("pittsburgh steelers", (None, "Steelers")),
    ("indianapolis colts", (None, "Colts")),
    ("jacksonville jaguars", (None, "Jaguars")),
    ("los angeles chargers", (None, "Chargers")),
    ("los angeles rams", (None, "Rams")),
    ("new york giants", (None, "Giants")),
    ("new york jets", (None, "Jets")),
    ("las vegas raiders", (None, "Raiders")),
    ("tampa bay", (None, "Buccaneers")),
    ("kansas city", (None, "Chiefs")),
    ("san francisco", (None, "49ers")),
    ("buffalo bills", (None, "Bills")),
    ("miami dolphins", (None, "Dolphins")),
    ("baltimore ravens", (None, "Ravens")),
    ("cleveland browns", (None, "Browns")),
    ("cincinnati bengals", (None, "Bengals")),
    ("houston texans", (None, "Texans")),
    ("tennessee titans", (None, "Titans")),
    ("denver broncos", (None, "Broncos")),
    ("dallas cowboys", (None, "Cowboys")),
    ("washington commanders", (None, "Commanders")),
    ("chicago bears", (None, "Bears")),
    ("detroit lions", (None, "Lions")),
    ("minnesota vikings", (None, "Vikings")),
    ("atlanta falcons", (None, "Falcons")),
    ("carolina panthers", (None, "Panthers")),
    ("arizona cardinals", (None, "Cardinals")),
    ("seattle seahawks", (None, "Seahawks")),
    ("chiefs", (None, "Chiefs")),
    ("49ers", (None, "49ers")),
    ("niners", (None, "49ers")),
    ("packers", (None, "Packers")),
    ("patriots", (None, "Patriots")),
    ("eagles", (None, "Eagles")),
    ("cowboys", (None, "Cowboys")),
    ("bills", (None, "Bills")),
    ("ravens", (None, "Ravens")),
    ("bengals", (None, "Bengals")),
    ("chargers", (None, "Chargers")),
    ("rams", (None, "Rams")),
    ("buccaneers", (None, "Buccaneers")),
    ("bucs", (None, "Buccaneers")),
]

NHL_TEAMS: list[tuple[str, tuple[str | None, str]]] = [
    ("toronto maple leafs", ("TOR", "Toronto Maple Leafs")),
    ("maple leafs", ("TOR", "Toronto")),
    ("montreal canadiens", ("MTL", "Montreal")),
    ("vancouver canucks", ("VAN", "Vancouver")),
    ("edmonton oilers", ("EDM", "Edmonton")),
    ("calgary flames", ("CGY", "Calgary")),
    ("ottawa senators", ("OTT", "Ottawa")),
    ("winnipeg jets", ("WPG", "Winnipeg")),
    ("boston bruins", ("BOS", "Boston")),
    ("buffalo sabres", ("BUF", "Buffalo")),
    ("detroit red wings", ("DET", "Detroit")),
    ("florida panthers", ("FLA", "Florida")),
    ("tampa bay lightning", ("TBL", "Tampa Bay")),
    ("new york rangers", ("NYR", "Rangers")),
    ("new york islanders", ("NYI", "Islanders")),
    ("new jersey devils", ("NJD", "Devils")),
    ("philadelphia flyers", ("PHI", "Philadelphia")),
    ("pittsburgh penguins", ("PIT", "Pittsburgh")),
    ("washington capitals", ("WSH", "Washington")),
    ("carolina hurricanes", ("CAR", "Carolina")),
    ("columbus blue jackets", ("CBJ", "Columbus")),
    ("chicago blackhawks", ("CHI", "Chicago")),
    ("colorado avalanche", ("COL", "Colorado")),
    ("dallas stars", ("DAL", "Dallas")),
    ("minnesota wild", ("MIN", "Minnesota")),
    ("nashville predators", ("NSH", "Nashville")),
    ("st louis blues", ("STL", "St. Louis")),
    ("st. louis blues", ("STL", "St. Louis")),
    ("anaheim ducks", ("ANA", "Anaheim")),
    ("arizona coyotes", ("ARI", "Arizona")),
    ("los angeles kings", ("LAK", "Los Angeles")),
    ("san jose sharks", ("SJS", "San Jose")),
    ("seattle kraken", ("SEA", "Seattle")),
    ("vegas golden knights", ("VGK", "Vegas")),
    ("leafs", ("TOR", "Toronto")),
    ("canadiens", ("MTL", "Montreal")),
    ("habs", ("MTL", "Montreal")),
    ("oilers", ("EDM", "Edmonton")),
    ("flames", ("CGY", "Calgary")),
    ("bruins", ("BOS", "Boston")),
    ("rangers", ("NYR", "Rangers")),
    ("penguins", ("PIT", "Pittsburgh")),
    ("capitals", ("WSH", "Washington")),
    ("caps", ("WSH", "Washington")),
    ("avalanche", ("COL", "Colorado")),
    ("avs", ("COL", "Colorado")),
    ("blackhawks", ("CHI", "Chicago")),
    ("lightning", ("TBL", "Tampa Bay")),
    ("golden knights", ("VGK", "Vegas")),
]


def extract_team(sport: str, question: str) -> tuple[str | None, str] | None:
    """Return (abbrev_or_None, like_fragment) if a known team is mentioned."""
    q = question.lower()
    table = {"nba": NBA_TEAMS, "nfl": NFL_TEAMS, "nhl": NHL_TEAMS}.get(sport, [])
    for alias, value in table:
        if alias in q:
            return value
    return None
